export const sceneGroups = [
  { id: "H0", slides: [1, 2], world: "Hong Kong sky -> city-level -> street overhead", job: "Define Metal AI OS and reject chatbot framing" },
  { id: "C1", slides: [3, 4, 5], world: "City signal layer over offices and tools", job: "Show AI moving from content generation to operating judgment" },
  { id: "C2", slides: [6, 7, 8, 9, 10], world: "Street / shop / back-office signal flow", job: "Show digitized-but-manual operations and revenue leaks" },
  { id: "M1", slides: [11, 12, 13, 14], world: "Clean model layer over the city", job: "Explain C / P / WTP and convert it into actions" },
  { id: "P1", slides: [15, 16, 17, 18], world: "Product control layer appears over business signals", job: "Show loop, inquiry demo, and core modules" },
  { id: "P2", slides: [19, 20, 21, 22, 23], world: "Workbench UI / system maps", job: "Show workspace, visibility, reception, quote gate, risk and review" },
  { id: "G1", slides: [24, 25, 26, 27], world: "Human-in-the-loop control layer", job: "Show agent preparation, human confirmation, controls, Daily Action Card" },
  { id: "A1", slides: [28, 29, 30, 31, 32], world: "Pilot path returns to Hong Kong business scene", job: "Show trial path, collaboration entry, and CTA" },
];

export const slides = [
  {
    number: 1,
    source: "S01",
    part: "Part 0",
    sceneGroup: "H0",
    pageType: "Cover",
    template: "hero-cinematic",
    title: "Metal AI OS",
    subtitle: "香港企業 AI 經營系統",
    body: [
      "由獲客、銷售、定價、成本到覆盤，將 AI 注入每日經營決策。",
      "不是多一個工具，而是一層把分散訊號轉成負責人、審批和下一步的經營判斷層。",
    ],
    visualType: "Hero / business signal scene",
    visualPurpose: "建立香港企業每日經營訊號正在被整理成決策的開場感",
    animation: "One-shot hero: camera starts above Hong Kong sky, descends to city-level title, then street-overhead subtitle.",
    needs: { image: true, diagram: false, ui: false },
    decision: "Confirm brighter Hong Kong references or approve generated/stock direction.",
  },
  {
    number: 2,
    source: "S02",
    part: "Part 0",
    sceneGroup: "H0",
    pageType: "One-liner",
    template: "statement-large",
    title: "Metal AI 不是你的 chatbot。",
    body: [
      "它每日幫你判斷：",
      "哪裏正在漏錢、誰應該先跟進、哪份報價要先審、哪個渠道值得繼續。",
    ],
    supporting: [
      "不是叫 AI 陪你聊天。",
      "是讓 AI 幫你每日看清：今日先做邊件事。",
    ],
    visualType: "Text-led contrast / operating decision frame",
    visualPurpose: "將觀眾由聊天式 AI 認知拉回每日經營判斷",
    animation: "Continue same hero shot; text slides from city-level to street-level business signals.",
    needs: { image: false, diagram: false, ui: false },
    decision: "Confirm whether this appears before or after full title hold.",
  },
  {
    number: 3,
    source: "D01",
    part: "Part 1｜時代背景",
    sceneGroup: "C1",
    pageType: "Part Divider",
    template: "chapter-break",
    title: "AI 不再只是生成內容。\n它開始參與經營判斷。",
    subtitle: "由內容生成，進入每日經營行動。",
    visualType: "Part Divider / full-screen image",
    visualPurpose: "作為時代背景章節開場，由內容生成轉入經營判斷",
    animation: "Content-generation particles become judgment signals inside the same city world.",
    needs: { image: true, diagram: false, ui: false },
  },
  {
    number: 4,
    source: "S03",
    part: "Part 1",
    sceneGroup: "C1",
    pageType: "Context Slide",
    template: "statement-with-visual",
    title: "AI 的下一步，不只是生成內容",
    body: ["老闆真正需要的不是更多文字，而是知道哪一件事要先處理、誰負責、依據是甚麼、要不要批准。"],
    supporting: ["內容生成只是輸出；經營判斷要連到資料、規則、負責人和結果追蹤。"],
    visualType: "Concept image / transition frame",
    visualPurpose: "展示 AI 由內容工具走向經營行動的轉變",
    animation: "Right-side signal layer forms a decision path.",
    needs: { image: true, diagram: false, ui: false },
  },
  {
    number: 5,
    source: "S04",
    part: "Part 1",
    sceneGroup: "C1",
    pageType: "Gap Slide",
    template: "system-map",
    title: "工具分散，行動就會分散",
    body: ["查詢在不同入口、資料在不同表格、報價在不同人手上，最後問題不是看不見，而是沒有進入同一條處理線。"],
    supporting: ["Metal AI OS 要做的是把訊號接回任務、草稿、審批和覆盤，而不是取代企業已有工具。"],
    visualType: "System map",
    visualPurpose: "展示多個工具各自記錄資料，但未形成同一套行動節奏",
    animation: "WhatsApp / IG / Email / form / phone nodes drift apart, then fail to enter one lane.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 6,
    source: "D02",
    part: "Part 2｜香港挑戰與機會",
    sceneGroup: "C2",
    pageType: "Part Divider",
    template: "chapter-break",
    title: "生意沒有消失。\n它只是散落在聊天記錄、報價單和表格裏。",
    subtitle: "真正的問題，是訊號未有及時變成行動。",
    visualType: "Part Divider / full-screen image",
    visualPurpose: "建立香港 SME 訊號流失和 Revenue Leak Map 心智",
    animation: "Street and back-office signals scatter across chat, quote, form surfaces.",
    needs: { image: true, diagram: false, ui: false },
  },
  {
    number: 7,
    source: "S05",
    part: "Part 2",
    sceneGroup: "C2",
    pageType: "Context Slide",
    template: "context-copy",
    title: "香港中小企已經數碼化，\n但經營判斷仍然靠人手。",
    body: [
      "支付、社交、搜尋、表單、POS、Excel 和 CRM 已經進入日常營運。",
      "下一步，不是再多裝一個工具，",
      "而是讓分散數據每日變成行動。",
    ],
    visualType: "Operating environment image",
    visualPurpose: "呈現數碼工具已進入營運，但判斷仍未自動形成行動",
    animation: "Existing tools appear as labels; the action line remains missing.",
    needs: { image: true, diagram: false, ui: false },
  },
  {
    number: 8,
    source: "S06",
    part: "Part 2",
    sceneGroup: "C2",
    pageType: "Pain Slide",
    template: "problem-list",
    title: "五個位置，最容易漏走生意。",
    items: [
      { title: "1. 商機分散，容易漏跟", body: "WhatsApp、IG、Email、表單和電話分散處理，客戶問過，但未必變成商機。" },
      { title: "2. 報價慢，客戶轉冷", body: "客戶有興趣，但資料未齊、報價慢、負責人不清，成交窗口被拖走。" },
      { title: "3. 報價發出後無人追", body: "不是沒有報價，而是報價之後沒有追單節奏。" },
      { title: "4. 折扣與毛利缺少守門人", body: "為了成交而亂減價，最後單做了，利潤卻變薄。" },
      { title: "5. 老闆看不到下一步優先次序", body: "數據很多，但不知道哪個渠道值得繼續、哪個客戶要先跟、哪個風險要先處理。" },
    ],
    visualType: "Pain-point list / leak map",
    visualPurpose: "讓觀眾清楚看見商機、報價、追單、毛利和優先次序的缺口",
    animation: "Five cards enter one by one; optional WTP / Q / P / C / Review strip can appear later.",
    needs: { image: false, diagram: true, ui: false },
    decision: "Confirm if optional WTP / Q / P / C / Review strip should appear.",
  },
  {
    number: 9,
    source: "S07",
    part: "Part 2",
    sceneGroup: "C2",
    pageType: "Opportunity Slide",
    template: "process-diagram",
    title: "機會在「訊號變行動」的速度",
    body: ["很多公司已經有查詢、產品資料、報價習慣和負責人；第一步不是重建一切，而是讓訊號更快進入處理線。"],
    supporting: ["一個清楚的下一步，比一堆散落資料更接近可管理的生意。"],
    visualType: "Process diagram",
    visualPurpose: "展示訊號、判斷、負責人和下一步之間的轉換關係",
    animation: "Scattered signals snap into one owner-and-next-step lane.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 10,
    source: "S08",
    part: "Part 2",
    sceneGroup: "C2",
    pageType: "Gap Slide",
    template: "layered-system",
    title: "記錄存在，不等於今日知道要做甚麼",
    body: ["保存記錄很重要，但老闆每天還需要一個判斷面：哪些查詢要跟、哪些報價要審、哪些風險要處理。"],
    supporting: ["Metal AI OS 補的是經營判斷層，讓資料可以進入任務、審批和覆盤。"],
    visualType: "Layered system diagram",
    visualPurpose: "區分資料記錄層和每日判斷層，說明 Metal AI 的工作位置",
    animation: "Record layer stays flat; judgment layer rises above it.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 11,
    source: "D03",
    part: "Part 3｜經營第一性原理",
    sceneGroup: "M1",
    pageType: "Part Divider",
    template: "chapter-break",
    title: "經營不是玄學。\n它始終回到 C、P、WTP。",
    subtitle: "成本、價格與客戶願付價，決定一盤生意的價值空間。",
    visualType: "Part Divider / data model diagram",
    visualPurpose: "作為 C / P / WTP 模型章節開場，建立理性和嚴謹感",
    animation: "City scene dims into clean model space.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 12,
    source: "S09",
    part: "Part 3",
    sceneGroup: "M1",
    pageType: "Model Slide",
    template: "model-diagram",
    title: "一盤生意，始終離不開三個數字。",
    definitions: [
      { key: "C", value: "完整交付成本" },
      { key: "P", value: "實際報價 / 成交價格" },
      { key: "WTP", value: "客戶願付價 / 感知價值" },
    ],
    formulas: ["企業利潤：P - C", "客戶剩餘：WTP - P", "總價值空間：WTP - C"],
    visualType: "Data model diagram",
    visualPurpose: "定義 C、P、WTP 三個經營數字和價值空間",
    animation: "C, P, WTP nodes draw in; equations appear after triangle stabilizes.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 13,
    source: "S10",
    part: "Part 3",
    sceneGroup: "M1",
    pageType: "Model Slide",
    template: "value-space-model",
    title: "好經營，是把價值空間拉大。",
    body: [
      "好經營不是單純加價，也不是盲目壓成本。",
      "真正要拉大的，是 WTP - C 這個價值空間。",
    ],
    items: [
      { title: "降低 C", body: "減少重複人手、錯誤報價、風險損失。" },
      { title: "管理 P", body: "報價規則、毛利底線、折扣審批。" },
      { title: "提高 WTP", body: "快速回應、可信資料、清晰服務、專業跟進。" },
    ],
    supporting: ["生意做得好，不只是賣貴一點。", "是成本少一點、報價準一點、客人覺得更值得。"],
    visualType: "Value-space model",
    visualPurpose: "說明降低 C、管理 P、提高 WTP 如何共同拉大價值空間",
    animation: "WTP-C gap expands; C lowers, P is guarded, WTP rises.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 14,
    source: "S11",
    part: "Part 3",
    sceneGroup: "M1",
    pageType: "Mechanism Slide",
    template: "action-mapping",
    title: "Metal AI 將經營模型變成每日行動。",
    items: [
      { title: "降低 C", body: "→ 自動整理詢盤、減少錯漏、減少重複跟進" },
      { title: "保護 P", body: "→ 報價草稿、毛利底線、折扣審批" },
      { title: "提高 WTP", body: "→ AI 能見度、快速回應、可信資料、評價與復購" },
    ],
    supporting: ["Metal AI 不只是 AI 工具。", "它把 C / P / WTP 轉成每日任務、審批與覆盤。"],
    visualType: "Action mapping diagram",
    visualPurpose: "將 C / P / WTP 轉成每日任務、審批與覆盤",
    animation: "Model transforms into three action rows.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 15,
    source: "D04",
    part: "Part 4｜Metal AI OS",
    sceneGroup: "P1",
    pageType: "Part Divider",
    template: "chapter-break",
    title: "從訊號，到行動。\n從行動，到覆盤。",
    subtitle: "把分散經營訊號，變成每日可處理的工作循環。",
    visualType: "Part Divider / product UI transition",
    visualPurpose: "把觀眾從經營模型帶入 Metal AI OS 產品和 Demo 部分",
    animation: "Model grid becomes Metal AI OS control surface.",
    needs: { image: true, diagram: false, ui: true },
  },
  {
    number: 16,
    source: "S12",
    part: "Part 4",
    sceneGroup: "P1",
    pageType: "Loop Slide",
    template: "process-loop",
    title: "每日經營循環",
    body: ["資料進入，AI 檢查與整理，發現缺口或商機，生成任務、草稿或審批項，人工確認後追蹤結果，再回到經營覆盤。"],
    supporting: ["每個判斷都要有來源、原因、紀錄或可解釋規則。"],
    steps: ["資料進入", "AI 檢查", "生成行動", "人工確認", "追蹤結果", "經營覆盤"],
    visualType: "Operating loop flow",
    visualPurpose: "展示資料進入、AI 檢查、生成行動、人工確認、追蹤結果和經營覆盤",
    animation: "Six loop steps draw clockwise.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 17,
    source: "S13",
    part: "Part 4",
    sceneGroup: "P1",
    pageType: "Demo Moment",
    template: "inquiry-branch",
    title: "一句「大概幾錢？」背後，\n其實有 5 個經營判斷。",
    message: "客戶：\n「下星期六 12 人活動，大概幾錢？」",
    outputs: [
      "商機：高意向",
      "報價：可生成草稿",
      "缺資料：預算 / 地點 / 時段",
      "風險：高峰期折扣需審批",
      "行動：今日 14:00 前補充資料",
    ],
    visualType: "Demo Moment / UI cards",
    visualPurpose: "讓非 AI 觀眾理解一條查詢如何變成商機、報價、缺資料、風險和今日行動",
    animation: "Customer message appears first; five cards branch out in order.",
    needs: { image: false, diagram: true, ui: true },
  },
  {
    number: 18,
    source: "S14",
    part: "Part 4",
    sceneGroup: "P1",
    pageType: "Module Slide",
    template: "module-map",
    title: "不是一堆功能。是一套經營 Loop。",
    modules: ["今日工作台", "AI 能見度", "商機接待", "報價與訂單", "經營風險提示", "經營報告與覆盤"],
    base: ["帳戶與資料管理", "權限 / 審批 / 日誌 / 可追溯資料"],
    visualType: "Product module map",
    visualPurpose: "展示 Metal AI 的核心板塊如何組成一套經營循環",
    animation: "Six modules attach around central loop; data governance base locks underneath.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 19,
    source: "S15",
    part: "Part 4",
    sceneGroup: "P2",
    pageType: "Module Slide",
    template: "ui-mock",
    title: "今日工作台：今天要處理甚麼",
    body: ["每日打開第一眼，應該看到要跟進的查詢、待批的報價、缺資料位置、風險提醒和覆盤下一步。"],
    supporting: ["工作台不是功能目錄，而是一張當日責任清單。"],
    visualType: "Product UI mock",
    visualPurpose: "展示今日待辦、審批與覆盤入口如何集中到工作台",
    animation: "Today workspace UI slides in with tasks, approvals, review entry.",
    needs: { image: false, diagram: false, ui: true },
  },
  {
    number: 20,
    source: "S16",
    part: "Part 4",
    sceneGroup: "P2",
    pageType: "Module Slide",
    template: "system-map",
    title: "AI 能見度：把外部訊號變成內部任務",
    body: ["公司在外面被怎樣理解、哪些資料不清楚、哪些內容需要補充，應該變成可分派和可覆核的任務。"],
    supporting: ["重點不是承諾外部結果，而是讓內部看到缺口、證據和下一步。"],
    visualType: "Signal-to-task system map",
    visualPurpose: "展示外部能見度訊號如何被整理成可檢查的內部任務",
    animation: "External signal becomes internal task card with source marker.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 21,
    source: "S17",
    part: "Part 4",
    sceneGroup: "P2",
    pageType: "Module Slide",
    template: "ui-mock",
    title: "商機接待：先整理，再回應",
    body: ["每條查詢先變成商機記錄：客戶想要甚麼、還缺甚麼資料、誰負責、草稿是否可以送審。"],
    supporting: ["回覆前先判斷，跟進後要留紀錄。"],
    visualType: "Product UI mock",
    visualPurpose: "展示查詢整理、缺資料標記、回應草稿和負責人分派",
    animation: "Inquiry is parsed into customer need, missing data, owner, draft.",
    needs: { image: false, diagram: false, ui: true },
  },
  {
    number: 22,
    source: "S18",
    part: "Part 4",
    sceneGroup: "P2",
    pageType: "Mechanism Slide",
    template: "approval-gate",
    title: "報價與訂單 Gate：先檢查，再送審",
    body: ["報價草稿要先連到來源查詢、價目表、毛利規則、折扣例外和審批紀錄，再交由人確認。"],
    supporting: ["Gate 的工作是把 source、rule、log 顯示出來，讓負責人知道為甚麼要審、審了甚麼、下一步由誰跟。"],
    steps: ["來源檢查", "價格規則", "折扣 Gate", "人工批准", "跟進隊列"],
    visualType: "Approval flow diagram",
    visualPurpose: "展示來源檢查、價格規則、折扣 Gate、人工批准和跟進隊列",
    animation: "Five gate steps animate left to right.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 23,
    source: "S19",
    part: "Part 4",
    sceneGroup: "P2",
    pageType: "Mechanism Slide",
    template: "governance-review",
    title: "AI 幫你快，\n不是幫你亂。",
    body: ["外發、改價、優惠、合同、資料導出，", "全部需要人工確認及日誌記錄。"],
    supporting: ["每週覆盤不只是報告，", "而是生成下一輪行動：", "哪些報價要追、哪些客戶可復購、哪個渠道值得繼續。"],
    visualType: "Governance and review frame",
    visualPurpose: "強調外發、改價、優惠、合同和資料導出都需要人工確認及紀錄",
    animation: "Risk actions lock behind human confirmation; review generates next action list.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 24,
    source: "D05",
    part: "Part 5｜Agent × Human",
    sceneGroup: "G1",
    pageType: "Part Divider",
    template: "chapter-break",
    title: "AI 處理複雜度。\n人保留最終承諾。",
    subtitle: "可控，才可以放進日常工作。",
    visualType: "Part Divider / collaboration system image",
    visualPurpose: "作為 Agent 與 Human 協作章節開場，強調可控才可放進日常工作",
    animation: "Agent layer and human confirmation layer separate visually.",
    needs: { image: true, diagram: false, ui: false },
  },
  {
    number: 25,
    source: "S20",
    part: "Part 5",
    sceneGroup: "G1",
    pageType: "Collaboration Slide",
    template: "human-loop",
    title: "Agent 準備，人做決定",
    body: ["Agent 整理訊號、提出判斷建議、準備草稿和證據；人確認是否採納、是否對外、由誰負責。"],
    supporting: ["這樣工作才可控，責任清楚，流程也可追蹤。"],
    visualType: "Human-in-the-loop process diagram",
    visualPurpose: "說明 Agent 負責整理和建議，人保留確認與承諾責任",
    animation: "Agent prepares; human confirms; responsibility remains visible.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 26,
    source: "S21",
    part: "Part 5",
    sceneGroup: "G1",
    pageType: "Mechanism Slide",
    template: "control-stack",
    title: "可控，才可以放進日常工作",
    body: ["每個重要動作都要知道來源、理由、誰可批准、留下甚麼紀錄，以及出錯時怎樣回到可處理狀態。"],
    supporting: ["安全不是口號，是每張行動卡上的證據、權限和審批路徑。"],
    steps: ["來源", "理由 / 規則", "審批", "紀錄 / 回滾"],
    visualType: "Control system diagram",
    visualPurpose: "展示來源、理由 / 規則、審批、紀錄 / 回滾四層控制機制",
    animation: "Source, reason/rule, approval, record/rollback stack upward.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 27,
    source: "S22",
    part: "Part 5",
    sceneGroup: "G1",
    pageType: "Action Card Slide",
    template: "action-card",
    title: "老闆不需要更多數據。\n老闆需要今天該做甚麼。",
    subtitle: "Daily Action Card：Quote #27",
    body: ["Quote #27 來自昨晚查詢，已對照活動套餐價目表。", "因為人數和日期已齊，但折扣超出規則，", "需要 May 在今日 18:00 前確認是否送審。"],
    fields: [
      { label: "負責人", value: "May" },
      { label: "截止時間", value: "今日 18:00" },
      { label: "證據", value: "來源查詢 / 套餐價目表 / 折扣規則" },
      { label: "狀態", value: "待審批" },
      { label: "寫回", value: "報價覆盤 / Quote #27" },
    ],
    visualType: "Daily Action Card / UI mock",
    visualPurpose: "以 Quote #27 展示老闆視角下的負責人、截止時間、證據、狀態和寫回位置",
    animation: "One large card becomes the main object; evidence badges appear after card body.",
    needs: { image: false, diagram: false, ui: true },
  },
  {
    number: 28,
    source: "D06",
    part: "Part 6｜由試點開始合作",
    sceneGroup: "A1",
    pageType: "Part Divider",
    template: "chapter-break",
    title: "先證明價值。\n再擴大系統。",
    subtitle: "從一條可驗證的經營 Loop 開始。",
    visualType: "Part Divider / pilot flow image",
    visualPurpose: "把觀眾從產品理解帶向合作行動，強調先試點再擴展",
    animation: "Control layer zooms out into pilot path.",
    needs: { image: true, diagram: false, ui: false },
  },
  {
    number: 29,
    source: "S23",
    part: "Part 6",
    sceneGroup: "A1",
    pageType: "Pilot Path Slide",
    template: "pilot-path",
    title: "先跑一條小型 Pilot 循環",
    body: ["由一組現有資料開始，指定一位負責人，設定一個審批口，跑出一份可覆盤的結果。"],
    supporting: ["後續是否擴展，要看這條循環是否真的產生可處理的每日行動。"],
    steps: ["查詢盤點", "7 日 Pilot", "30 日覆盤", "擴展決策"],
    visualType: "Pilot process diagram",
    visualPurpose: "展示查詢盤點、7 日 Pilot、30 日覆盤和擴展決策",
    animation: "Query audit -> 7 day Pilot -> 30 day Review -> expansion decision.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 30,
    source: "S24",
    part: "Part 6",
    sceneGroup: "A1",
    pageType: "Pilot Path Slide",
    template: "pilot-checklist",
    title: "第一階段，只要足夠跑通循環",
    body: ["先準備查詢樣本、產品或服務資料、報價規則、負責人名單和覆盤格式。"],
    supporting: ["資料不需要一次過完整；先讓一條工作線可以進入檢查、審批和覆盤。"],
    steps: ["查詢", "產品資料", "報價規則", "負責人", "覆盤格式"],
    visualType: "Pilot input checklist",
    visualPurpose: "對齊第一階段所需的查詢、產品資料、報價規則、負責人和覆盤格式",
    animation: "Five input cards appear as minimum operating kit.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 31,
    source: "S25",
    part: "Part 6",
    sceneGroup: "A1",
    pageType: "Collaboration Slide",
    template: "role-entry-map",
    title: "不同角色，不同合作入口。",
    entries: [
      { role: "中小企客戶", action: "申請商機 / 報價試點" },
      { role: "合作夥伴", action: "聯合獲客、行業方案、渠道合作" },
      { role: "技術供應商", action: "按 PoC 範圍與驗收標準交付" },
      { role: "投資者", action: "參與 AI Revenue Loop 基礎設施建設" },
    ],
    visualType: "Stakeholder entry map",
    visualPurpose: "區分中小企客戶、合作夥伴、技術供應商和投資者的合作入口",
    animation: "Four entry cards appear by role.",
    needs: { image: false, diagram: true, ui: false },
  },
  {
    number: 32,
    source: "S26",
    part: "Part 6",
    sceneGroup: "A1",
    pageType: "CTA Slide",
    template: "cta-final",
    title: "讓香港企業，不再只靠感覺經營。",
    body: ["從一條詢盤開始。", "把它變成商機、報價、風險、任務和覆盤。"],
    supporting: ["生意可以有感覺，", "但經營不能只靠感覺。"],
    cta: ["申請首輪試點", "預約產品演示", "成為合作夥伴"],
    visualType: "Closing action frame",
    visualPurpose: "將詢盤、商機、報價、風險、任務和覆盤收束到三個合作行動",
    animation: "Return to Hong Kong business scene; three CTA buttons lock into place.",
    needs: { image: false, diagram: false, ui: true },
    decision: "Confirm final CTA priority order if it changes.",
  },
];

export const templates = [...new Set(slides.map((slide) => slide.template))];

export default slides;
